### PR TITLE
Bump CAPVCD version to 1.1.0

### PR DESCRIPTION
**Pull request by erkanerol**
Consumes the new `giantswarm-1.1.z` branch.

Towards https://github.com/giantswarm/giantswarm/issues/27464

### Testing

- [ ] fresh install works
- [x] upgrade from previous version works

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [ ] Update lastpass values if required.

### CODE REVIEW

**Review by vxav — APPROVED** [review]

**Comment by erkanerol** [comment]
Please don't merge this until CAPI bug is fixed.

**Review by jkremser — APPROVED** [review]

**Comment by jkremser** [comment]
> Please don't merge this until CAPI bug is fixed.

could you be more specific?

**Comment by erkanerol** [comment]
> > Please don't merge this until CAPI bug is fixed.
> 
> could you be more specific?

I mentioned it in the parent issue here https://github.com/giantswarm/giantswarm/issues/27464#issuecomment-1649398066

**Comment by erkanerol** [comment]
I verified this PR with the latest CAPI version so we can merge this PR.

**Pull request merged**
